### PR TITLE
Rework the configuration to be more conditional

### PR DESCRIPTION
**Pull request by drybjed**

### CODE REVIEW

**Comment by drybjed** [comment]
@ypid I tried your approach with `/env` and assertion, but i hadn't changed the old address list, ie. didn't have any subnetwork addresses set. Role instantly stopped, which irked me, so I want to change how this works. What do you think about this approach? Playbook will be updated separately, obviously.

**Comment by ypid** [comment]
@drybjed I added the test because I was using the role again and wrongly entered a network address and then had to do some debugging to find the problem. Can we still give a hint, in this case :wink: ?

**Comment by drybjed** [comment]
@ypid I've added some docs that explain that a valid CIDR subnet needs to be configured. In any case, I prefer when roles skip rather than failing, perhaps it's due to how I'm using the main playbook... I don't want to fail the playbook which would prevent configuration of some other thing further down. Perhaps skipping might be less intuitive?

Ansible doesn't have a good user feedback mechanism in case something needs to be set, `debug` tasks doesn't really work for this. I suppose that sanest method so far would be to mail the user in case of issues like this. On the other hand, once you "fix the issue", ie. make the role work and know how to set it in the future, additional code that handles the errors becomes not very useful, since role works all the time now. So again, better documentation is probably the best way to handle this.

I had an idea to upgrade the `debops.subnetwork` role to handle multiple bridges and subnets similar to how `debops.tinc` was rewritten, with `debops.subnetwork` essentially just generating configuration for `debops.ifupdown` and `debops.ferm`. The lone task that removes the old `ferm` configuration could be dropped then. Maybe in some time I or someone else could try it out.

**Comment by ypid** [comment]
@drybjed I guess we have different use cases. I normally try new configuration on a test system iteratively and like direct feedback when I wrote invalid configuration. But better documentation and sending emails is probably better …

**Comment by thiagotalma** [comment]
Hello guys!  @drybjed @ypid 
This change broke the devops!

```
ERROR! the role 'debops.subnetwork/env' was not found in /debops/ansible/playbooks/../debops-playbooks/playbooks/net/roles:/debops/ansible/playbooks/../debops-playbooks/playbooks/net:/debops/ansible/roles:/debops/roles:/debops/ansible/roles:/debops/ansible/debops-playbooks/playbooks/../roles:/debops/ansible/debops-playbooks/playbooks/roles:/etc/ansible/roles

The error appears to have been in '/debops/ansible/debops-playbooks/playbooks/net/subnetwork.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - role: debops.subnetwork/env
      ^ here
```

**Pull request merged**
