### PR TITLE
Rework and features

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by ypid** [comment]
(FIXME: Disabled assert_playbook_idempotent for debops.subnetwork)[https://github.com/debops/test-suite/commit/568d07db0d938a0cc02a2ae63f65b4140a46155f]
I don’t see an easy way to fix this. Am I missing something?

**Comment by drybjed** [comment]
I'm gonna look into the idempotency issue shortly.

**Comment by ypid** [comment]
@drybjed Maybe just run the playbook two times before `assert_playbook_idempotent`?

**Comment by drybjed** [comment]
@ypid Hmmm, that kinda defeats the idea of idempotency...

BN, `debops.ifupdown` is due for an overhaul. I would merge this PR and any PRs related to `debops.ifupdown` elsewhere to not lose the work and tag any related roles before messing with `ifupdown` too much. What do you think?

**Comment by ypid** [comment]
Sounds like an idea. OK :wink:

**Pull request merged**
